-- Enterprise single sign-on (OIDC + SAML 2.0), applied after the baseline.
--
-- Previously split across two migrations (add_sso_connections, add_saml_sso);
-- folded into one additive migration so the SSO feature keeps a single
-- release boundary. Generated by Prisma as the diff from the pre-SSO schema to
-- the current schema.
--
-- Additive only (one new table plus its indexes and foreign key), so it cannot
-- lock or rewrite existing tables. The IdP client secret is never stored in
-- plaintext; it is written to "clientSecretEncrypted" (AES-256-GCM, key from
-- SSO_ENCRYPTION_KEY or WEBHOOK_ENCRYPTION_KEY). The unique (tenantId) keeps
-- the login flow unambiguous: an email domain maps to at most one tenant IdP.

-- CreateTable
CREATE TABLE "sso_connections" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'OIDC',
    "issuerUrl" TEXT,
    "clientId" TEXT,
    "clientSecretEncrypted" TEXT,
    "idpEntityId" TEXT,
    "idpSsoUrl" TEXT,
    "idpCertificate" TEXT,
    "spEntityId" TEXT,
    "scopes" TEXT NOT NULL DEFAULT 'openid email profile',
    "allowedEmailDomains" JSONB,
    "autoProvision" BOOLEAN NOT NULL DEFAULT true,
    "defaultRole" "UserRole" NOT NULL DEFAULT 'STAFF',
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "metadata" JSONB,
    "createdBy" TEXT,
    "lastUsedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "sso_connections_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "sso_connections_enabled_idx" ON "sso_connections"("enabled");

-- CreateIndex
CREATE UNIQUE INDEX "sso_connections_tenantId_key" ON "sso_connections"("tenantId");

-- AddForeignKey
ALTER TABLE "sso_connections" ADD CONSTRAINT "sso_connections_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

